# -*- coding: utf-8 -*-
"""Road Damage Detection System .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dYF6R3zJGWf63K-ZHTUs-ar7vvU3w1M
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="M9AvNYakfCgJhMbjcENi")
project = rf.workspace("nours-workspace-tt6rt").project("rdd-ww7ev-cptsy")
version = project.version(1)
dataset = version.download("yolov8")

!pip install ultralytics
from ultralytics import YOLO
import os
os.listdir('/content')

print(os.listdir('/content'))

dataset_path = "/content/rdd-1"
print(os.listdir(dataset_path))

# * Data Preprocessing for Road Damage Detection
# * Cleaning + Verification + Basic Augmentation

import cv2

dataset_path = "/content/rdd-1"
splits = ['train', 'valid', 'test']

deleted_images = 0
deleted_labels = 0

print("Starting dataset cleaning... 🧹")

# * Step 1: Remove corrupted images and missing labels

for split in splits:
    images_dir = os.path.join(dataset_path, split, 'images')
    labels_dir = os.path.join(dataset_path, split, 'labels')

    for img_file in os.listdir(images_dir):
        img_path = os.path.join(images_dir, img_file)
        label_path = os.path.join(labels_dir, img_file.replace('.jpg', '.txt'))

        # Check if image is readable
        img = cv2.imread(img_path)

        if img is None:
            os.remove(img_path)
            deleted_images += 1

            if os.path.exists(label_path):
                os.remove(label_path)
                deleted_labels += 1
            continue

        # Check if label exists
        if not os.path.exists(label_path):
            os.remove(img_path)
            deleted_images += 1




# * Step 2: Remove empty labels
# * // I used ai tools
for split in splits:
    labels_dir = os.path.join(dataset_path, split, 'labels')
    images_dir = os.path.join(dataset_path, split, 'images')

    for label_file in os.listdir(labels_dir):
        label_path = os.path.join(labels_dir, label_file)

        if os.path.getsize(label_path) == 0:
            os.remove(label_path)
            deleted_labels += 1

            img_file = label_file.replace('.txt', '.jpg')
            img_path = os.path.join(images_dir, img_file)

            if os.path.exists(img_path):
                os.remove(img_path)
                deleted_images += 1

print(f"Deleted images: {deleted_images}")
print(f"Deleted labels: {deleted_labels}")



# * Step 3: Dataset summary

for split in splits:
    images_dir = os.path.join(dataset_path, split, 'images')
    labels_dir = os.path.join(dataset_path, split, 'labels')

    print(f"{split.upper()} -> Images: {len(os.listdir(images_dir))}, Labels: {len(os.listdir(labels_dir))}")
print("✅ Dataset preprocessing finished")

# * Set dataset path


dataset_path = "/content/rdd-1"

data_yaml = dataset_path + "/data.yaml"
print("Using dataset:", data_yaml)

# * Load pretrained YOLOv8 model



model = YOLO("yolov8s.pt")

# Train YOLOv8 model


results = model.train(
    data=data_yaml,
    epochs=50,
    imgsz=640,
    batch=16,
    optimizer="Adam",
    lr0=0.001,
    name="road_damage_model_v2",
    augment=True,
    patience=20,
)

# Evaluate the model on validation set
metrics = model.val()

print("Evaluation Results:")
print("Precision:", metrics.box.p)
print("Recall:", metrics.box.r)
print("mAP50:", metrics.box.map50)
print("mAP50-95:", metrics.box.map)

results = model.predict(
    source="/content/rdd-1/test/images",
    conf=0.3,
    save=True,
    show=False, # Changed to False to prevent display errors in Colab
    augment=True
)

for result in results:
    boxes = result.boxes
    print(f"Detected damages count: {len(boxes)}")  # Damage Counting

    for box in boxes:
        # Calculate area to estimate severity
        x1, y1, x2, y2 = box.xyxy[0]
        area = (x2 - x1) * (y2 - y1)

        if area < 5000:
            severity = "Low"
        elif area < 15000:
            severity = "Medium"
        else:
            severity = "High"

        print(f"Damage type: {model.names[int(box.cls)]}, Severity: {severity}")

from IPython.display import Image, display
import os

folder = "runs/detect/predict"

for img in os.listdir(folder):
    display(Image(filename=os.path.join(folder, img)))


    print(model.names)

model = YOLO("yolov8s.pt")
results2 = model.train(
    data=data_yaml,
    epochs=30,
    imgsz=640,
    batch=16,
    optimizer="Adam",
    lr0=0.001,
    name="road_damage_model_v2",
    augment=True,
    patience=20,
)

model.val(name="road_damage_eval")

model = YOLO("yolov8s.pt")
results3 = model.train(
    data=data_yaml,
    epochs=30,
    imgsz=640,
    batch=16,
    optimizer="Adam",
    lr0=0.001,
    name="road_damage_no_aug_exp3",
    augment=False,
    patience=20,
)